# NumPy : Day 1 - The Absolute Essentials

### Goals:
By the end of this session, you will be able to:
1.  Explain **why** NumPy is fundamental for data science in Python.
2.  Create 1D and 2D NumPy arrays from scratch.
3.  Inspect the essential attributes of an array (shape, size, data type).
4.  Understand and perform **vectorized** operations (element-wise math).
5.  Appreciate the performance difference between NumPy arrays and Python lists.

## Part 1: The "Why" - Introduction to NumPy 

### What problem does NumPy solve?

Imagine you have a Python list of one million numbers and you want to add 5 to every single number. How would you do it using plain Python?

In [2]:
# The "slow" way with Python lists
python_list = list(range(1_000_000))

# We'll use the time module to see how long this takes
import time
start_time = time.time()

new_list = []
for item in python_list:
    new_list.append(item + 5)
    
end_time = time.time()
print(f"Python list took: {end_time - start_time:.4f} seconds")
print(f"First 10 elements of the new list: {new_list[:10]}")

Python list took: 0.1981 seconds
First 10 elements of the new list: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


### NumPy as the Solution

NumPy stands for **Numerical Python**. It's the foundational package for scientific computing in Python.

**The Three Pillars of NumPy:**
1.  **Speed:** NumPy operations are implemented in a low-level language (C), making them much faster than native Python loops.
2.  **Memory Efficiency:** NumPy arrays take up less space in memory than Python lists.
3.  **Convenience:** Provides a huge library of high-level mathematical functions that operate on arrays.

--- 
### The Core Object: The `ndarray`

The heart of NumPy is the `numpy.ndarray` (n-dimensional array).

**Key Characteristic:** An array contains elements of the **same data type**. This is a crucial difference from a Python list, which can hold anything. 

**Analogy:** A Python list is a generic grocery bag (you can put an apple, a milk carton, and keys inside). A NumPy array is an egg carton (it's specifically designed to hold only eggs, and they're all arranged neatly in a grid).

## Part 2: Getting Started - Creating Arrays 

### Installation & The Standard Convention

First, you need to install NumPy. You can do this from your terminal (not in the notebook):
```sh
pip install numpy
```

Once installed, we import it into our project. The standard, community-accepted convention is to import it with the alias `np`.

In [3]:
import numpy as np

### Creating Arrays from Python Lists

The most basic way to create an array is using `np.array()` on an existing Python list.

In [4]:
# Creating a 1-Dimensional array (also called a vector)
list_a = [1, 2, 3, 4]
array_a = np.array(list_a)

print(array_a)
print(type(array_a))
print(np.ndim(array_a))
print(np.shape(array_a))
array_a.dtype

[1 2 3 4]
<class 'numpy.ndarray'>
1
(4,)


dtype('int64')

In [5]:
# Creating a 2-Dimensional array (also called a matrix)
list_b = [[1, 2, 3], [4, 5, 6]]
array_b = np.array(list_b)

print(array_b)
print(np.ndim(array_b))
print(np.shape(array_b))


array_b.dtype

[[1 2 3]
 [4 5 6]]
2
(2, 3)


dtype('int64')

In [6]:
# 3- D array  :( x, y , z)

list_c = [[[1, 2, 3], [4, 5, 6]],  [[7,8,9], [10,11,12]]]     # shape ko lagi hamiley [] hernu parxa 
                                                               # yesko vitra part ma x,y,z miley ko huna parxa 
array_c = np.array(list_c)

print(array_c)
print(np.ndim(array_c))
print(np.shape(array_c))


array_c.dtype

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


dtype('int64')

In [7]:
#try  4- D array 
list_d = [[[[1, 2, 3,13], [4, 5, 6,14]],  [[7,8,9,15], [10,11,12,16]]]]     # shape ko lagi hamiley [] hernu parxa 
                                                               # yesko vitra part ma x,y,z miley ko huna parxa 
array_d = np.array(list_d)

print(array_d)
print(np.ndim(array_d))
print(np.shape(array_d))


array_d.dtype

[[[[ 1  2  3 13]
   [ 4  5  6 14]]

  [[ 7  8  9 15]
   [10 11 12 16]]]]
4
(1, 2, 2, 4)


dtype('int64')

### More Efficient Array Creation Routines

It's often inefficient to create a large Python list first. NumPy provides built-in functions for creating arrays from scratch.

#### `np.arange(start, stop, step)`
Similar to Python's built-in `range()`, but it returns a NumPy array.

In [8]:
# An array from 0 up to (but not including) 10
array_c = np.arange(0, 10)          # yo normal arrange haina 
print(array_c)

print(array_c)
print(np.ndim(array_c))             # 1-D ma rnage comma nothig huncxa 
print(np.shape(array_c))


array_c.dtype

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
1
(10,)


dtype('int64')

#### `np.zeros()` and `np.ones()`
Create arrays of a given shape filled entirely with 0s or 1s. This is very useful for creating placeholder arrays that you'll fill with data later.

In [9]:
# A 1D array of 5 zeros
zeros_array = np.zeros(5   )
print(zeros_array)

# A 2D array (3 rows, 4 columns) of ones
# Note: The shape is passed as a tuple: (3, 4)
ones_array = np.ones((3, 4))
print("\n", ones_array)

[0. 0. 0. 0. 0.]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### `np.linspace(start, stop, num)`
Creates an array with a specific number of evenly spaced points between a start and end value (inclusive). Very useful for plotting functions.

In [10]:
# Create 5 evenly spaced points from 0 to 100 (inclusive)
linspace_array = np.linspace(0, 100, 5)
print(linspace_array)

# Create 10 evenly spaced points from 0 to 1
linspace_array_2 = np.linspace(0, 1, 10)
print("\n", linspace_array_2)

[  0.  25.  50.  75. 100.]

 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## Part 3: Inspecting Your Array - The Attributes 

Once you have an array, how do you get information about it without printing the whole thing? We use array attributes.

**Note:** These are attributes, not methods, so you don't use parentheses `()` at the end.

In [11]:
# Let's create a sample 2D array to inspect
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("The array is:")
print(data)
print("-"*20)

# .shape: The dimensions of the array (rows, columns)
print("Shape:", data.shape) 

# .ndim: The number of dimensions (or axes)
print("Dimensions:", data.ndim) 

# .size: The total number of elements in the array
print("Size:", data.size) 

# .dtype: The data type of the elements in the array
print("Data Type:", data.dtype)

The array is:
[[1 2 3 4]
 [5 6 7 8]]
--------------------
Shape: (2, 4)
Dimensions: 2
Size: 8
Data Type: int64


In [12]:
## Indexing and slicing 

data = [[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]]
arr = np.array(data )
print(arr)
print(arr.ndim, arr.shape, arr.dtype, type(arr))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
3 (2, 3, 3) int64 <class 'numpy.ndarray'>


In [13]:
arr[0][1][2]

np.int64(6)

In [14]:
data[0][1][1]

5

In [15]:
#data[0,1,1]   # list indices must be in inttegers or slices, not tuple 

In [16]:
arr[0,1,1]

np.int64(5)

In [17]:
arr[0].ndim

2

In [18]:
#for slicing  

arr[0,1:,:2]

array([[4, 5],
       [7, 8]])