In [4]:
import numpy as np 


In [5]:
print ('Hello World !')

Hello World !


In [6]:
import sklearn 

In [7]:
i = 45

In [8]:
print (7)

7


In [9]:
i

45

# Welcome to numpy tutorial 

***Mohit Tharu***

In [10]:
import numpy as np 

In [11]:
myarr = np.array([ 1, 2, 3], np.int8)       

In [12]:
myarr[0, 1]        

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
myarr = np.array([[ 1, 2, 3]], np.int8)    # 2-D array 

In [ ]:
myarr[0,1]

In [ ]:
myarr.dtype

In [13]:
myarr.shape

(3,)

In [14]:
myarr.size 

3

In [15]:
myarr[0 , 1] = 45       # array change garna ko lagi 

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [16]:
myarr

array([1, 2, 3], dtype=int8)

# There are 5 general mechanism for creating arrays :
1. conversion from other python structures (eg. lists , tuples)
2. intrinsic numpy array creation objects (eg. arange , ones ,zeros etc )
3. reading arrays from disk , either from standard or custom formats 
4. creating arrays from raw bytes through the use of strings or buffers 
5. use of special library functions (eg. random )

# Conversion from other Python Structures 

In [17]:
listarray= np.array([[1 ,2 ,3 ], [4, 5, 6 ], [7 ,8 ,9 ]])

In [18]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
listarray.dtype

dtype('int64')

In [20]:
listarray.size

9

In [21]:
listarray.shape

(3, 3)

In [22]:
np.array({3, 2, 1 })

array({1, 2, 3}, dtype=object)

In [23]:
zeros = np.zeros((2, 5))

In [24]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
rng = np.arange(15)

In [26]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
lspace= np.linspace(1, 5, 12)     #( start, last , lenspace)

In [28]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [29]:
emp = np.empty((4, 6))     # khali array with random nbr

In [30]:
emp

array([[6.23042070e-307, 1.42417221e-306, 1.60219306e-306,
        7.56593017e-307, 7.56587584e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.69118108e-306],
       [2.22522597e-306, 1.78020848e-306, 1.37962185e-306,
        9.34609790e-307, 1.11260619e-306, 8.45593934e-307],
       [1.42418172e-306, 8.06610918e-308, 6.89810244e-307,
        1.22387550e-307, 2.22522596e-306, 2.22522596e-306]])

In [31]:
emp_like = np.empty_like(lspace)    # 

In [32]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [33]:
ide = np.identity((45))

In [34]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [35]:
ide.shape

(45, 45)

In [36]:
arr = np.arange(99)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
arr.reshape(3,33)          # 3 list ma divide garxa 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr= arr.ravel()

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr.shape

(99,)

In [43]:
## here numpy AXIS
1-D : [1, 2, 3, 4, 5]     --> 1 ( axis 0)

2-D : [[1, 2, 3, 4],   
       [4, 5, 6, 7] ]             --> 1 ( axis 0    ,   axis 1)

SyntaxError: illegal target for annotation (1501678538.py, line 2)

In [46]:
x = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

In [47]:
ar = np.array(x)

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
ar.sum(axis = 0)

array([12, 15, 18])

In [50]:
ar.sum(axis = 1)

array([ 6, 15, 24])

In [51]:
ar.T        # Transpose use vayeko xa 

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [53]:
ar.flat

In [55]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [56]:
ar.ndim    # ndim dimensional ko lagi use humxa

2

In [57]:
ar.size

9

In [58]:
ar.shape

(3, 3)