In [5]:
# The "slow" way with Python lists
python_list = list(range(1_000_000))

# We'll use the time module to see how long this takes
import time
start_time = time.time()

new_list = []
for item in python_list:
    new_list.append(item + 5)
    
end_time = time.time()
print(f"Python list took: {end_time - start_time:.4f} seconds")
print(f"First 10 elements of the new list: {new_list[:10]}")

Python list took: 0.2567 seconds
First 10 elements of the new list: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


### NumPy as the Solution

NumPy stands for **Numerical Python**. It's the foundational package for scientific computing in Python.

**The Three Pillars of NumPy:**
1.  **Speed:** NumPy operations are implemented in a low-level language (C), making them much faster than native Python loops.
2.  **Memory Efficiency:** NumPy arrays take up less space in memory than Python lists.
3.  **Convenience:** Provides a huge library of high-level mathematical functions that operate on arrays.

--- 
### The Core Object: The `ndarray`

The heart of NumPy is the `numpy.ndarray` (n-dimensional array).

**Key Characteristic:** An array contains elements of the **same data type**. This is a crucial difference from a Python list, which can hold anything. 

**Analogy:** A Python list is a generic grocery bag (you can put an apple, a milk carton, and keys inside). A NumPy array is an egg carton (it's specifically designed to hold only eggs, and they're all arranged neatly in a grid).

## Part 2: Getting Started - Creating Arrays (25 minutes)

### Installation & The Standard Convention

First, you need to install NumPy. You can do this from your terminal (not in the notebook):
```sh
pip install numpy
```

Once installed, we import it into our project. The standard, community-accepted convention is to import it with the alias `np`.

In [6]:
import numpy as np

### Creating Arrays from Python Lists

The most basic way to create an array is using `np.array()` on an existing Python list.

In [7]:
# Creating a 1-Dimensional array (also called a vector)
list_a = [1, 2, 3, 4]
array_a = np.array(list_a)

print(array_a)
print(type(array_a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
# Creating a 2-Dimensional array (also called a matrix)
list_b = [[1, 2, 3], [4, 5, 6]]
array_b = np.array(list_b)

print(array_b)

[[1 2 3]
 [4 5 6]]


### More Efficient Array Creation Routines

It's often inefficient to create a large Python list first. NumPy provides built-in functions for creating arrays from scratch.

#### `np.arange(start, stop, step)`
Similar to Python's built-in `range()`, but it returns a NumPy array.

In [9]:
# An array from 0 up to (but not including) 10
array_c = np.arange(0, 10)
print(array_c)

[0 1 2 3 4 5 6 7 8 9]


#### `np.zeros()` and `np.ones()`
Create arrays of a given shape filled entirely with 0s or 1s. This is very useful for creating placeholder arrays that you'll fill with data later.

In [10]:
# A 1D array of 5 zeros
zeros_array = np.zeros(5)
print(zeros_array)

# A 2D array (3 rows, 4 columns) of ones
# Note: The shape is passed as a tuple: (3, 4)
ones_array = np.ones((3, 4))
print("\n", ones_array)

[0. 0. 0. 0. 0.]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### `np.linspace(start, stop, num)`
Creates an array with a specific number of evenly spaced points between a start and end value (inclusive). Very useful for plotting functions.

In [11]:
# Create 5 evenly spaced points from 0 to 100 (inclusive)
linspace_array = np.linspace(0, 100, 5)
print(linspace_array)

# Create 10 evenly spaced points from 0 to 1
linspace_array_2 = np.linspace(0, 1, 10)
print("\n", linspace_array_2)

[  0.  25.  50.  75. 100.]

 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## Part 3: Inspecting Your Array - The Attributes (15 minutes)

Once you have an array, how do you get information about it without printing the whole thing? We use array attributes.

**Note:** These are attributes, not methods, so you don't use parentheses `()` at the end.

In [12]:
# Let's create a sample 2D array to inspect
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("The array is:")
print(data)
print("-"*20)

# .shape: The dimensions of the array (rows, columns)
print("Shape:", data.shape) 

# .ndim: The number of dimensions (or axes)
print("Dimensions:", data.ndim) 

# .size: The total number of elements in the array
print("Size:", data.size) 

# .dtype: The data type of the elements in the array
print("Data Type:", data.dtype)

The array is:
[[1 2 3 4]
 [5 6 7 8]]
--------------------
Shape: (2, 4)
Dimensions: 2
Size: 8
Data Type: int64


## Part 4: The Magic - Basic Math and Vectorization (25 minutes)

### The Core Concept: Vectorization

This is the payoff! Let's revisit our initial problem of adding 5 to one million numbers, but this time, we'll use NumPy.

In [13]:
# The "fast" way with NumPy
numpy_array = np.arange(1_000_000)

# Start the timer
start_time = time.time()

# This is vectorization! The operation is applied to every element.
result_array = numpy_array + 5 

end_time = time.time()
print(f"NumPy array took: {end_time - start_time:.4f} seconds") 
print(f"First 10 elements of the result array: {result_array[:10]}")

NumPy array took: 0.0041 seconds
First 10 elements of the result array: [ 5  6  7  8  9 10 11 12 13 14]


**Vectorization** is the process of performing an operation on the entire array at once, without needing an explicit Python `for` loop. This is the heart of NumPy's power and convenience.

### Element-wise Operations

All standard mathematical operations work in a vectorized, element-wise fashion.

#### Array-Scalar Operations

In [14]:
arr = np.array([10, 20, 30, 40])

print("Original:", arr)
print("Addition:", arr + 5)      
print("Subtraction:", arr - 10)
print("Multiplication:", arr * 2) 
print("Division:", arr / 10)
print("Power:", arr ** 2)

Original: [10 20 30 40]
Addition: [15 25 35 45]
Subtraction: [ 0 10 20 30]
Multiplication: [20 40 60 80]
Division: [1. 2. 3. 4.]
Power: [ 100  400  900 1600]


#### Array-Array Operations
To perform an operation between two arrays, they must have the same shape.

In [15]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("a:", a)
print("b:", b)
print("a + b:", a + b)
print("a * b:", a * b)

a: [1 2 3]
b: [10 20 30]
a + b: [11 22 33]
a * b: [10 40 90]


In [16]:
# This also works for 2D arrays!
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.ones((2, 2))

print("Matrix A:\n", matrix_a)
print("\nMatrix B:\n", matrix_b)
print("\nMatrix A + Matrix B:\n", matrix_a + matrix_b)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[1. 1.]
 [1. 1.]]

Matrix A + Matrix B:
 [[2. 3.]
 [4. 5.]]


In [ ]:
#### dot is used for multiplication 


In [ ]:
# Boolean Indexing 
- it allows us to filter elements from an array based on given condition .
-we use boolean mask to specify condition
- booolean mask in a numpy array contain truth values (T/F) that sorrespond to each element in the array 


In [17]:
arr = np.random.randint(50, size=(4,5))
arr

array([[ 6, 14, 23, 42,  5],
       [39, 12, 14,  0, 29],
       [40,  5, 46, 39,  9],
       [24, 32, 43, 17, 27]], dtype=int32)

In [18]:
boolean_mask = arr>30
arr[boolean_mask]

array([42, 39, 40, 46, 39, 32, 43], dtype=int32)

In [19]:
arr[arr<30] = 0

In [20]:
arr

array([[ 0,  0,  0, 42,  0],
       [39,  0,  0,  0,  0],
       [40,  0, 46, 39,  0],
       [ 0, 32, 43,  0,  0]], dtype=int32)

In [ ]:
#Fancy Indexing 
-Fancy Indexing allows us to use an array of indices to access multiple array-elements at once 
-it can perfform more addvanced and efficient array operation , indexing conditional , sorting and so on 




In [21]:
data = [1,2,3,4,5,6,7,8,9]
data[4]
data[0:5]
data[4:]
data[::2]

#1,5,6,9    hudaina ekai palta
#data[0,4,5,8]

[1, 3, 5, 7, 9]

In [22]:
arr = np.array(data)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[4::2]

array([5, 7, 9])

## Part 5: Wrap-up & Mini-Challenge (10 minutes)

### Recap of Key Concepts

*   NumPy is for **numerical** data and is **fast**, **memory-efficient**, and **convenient**.
*   The core object is the `ndarray`, which holds a grid of **same-typed** data.
*   We create arrays with `np.array()`, `np.arange()`, `np.zeros()`, `np.linspace()`.
*   We inspect them with the attributes `.shape`, `.ndim`, `.size`, `.dtype`.
*   **Vectorization** is the magic that lets us perform math on entire arrays without loops, and it's the key to writing clean and fast NumPy code.

### Mini-Challenge: Celsius to Fahrenheit

You have a list of temperatures in Celsius. Your task is to convert them to Fahrenheit.

**Formula:** `F = C * 1.8 + 32`

In [ ]:
celsius_temps = [0, 10, 20, 25, 30, 40, 100]

# Your task:
# 1. Create a NumPy array from the celsius_temps list.


# 2. Perform the vectorized calculation to convert them to Fahrenheit.


# 3. Print the resulting Fahrenheit temperatures.



--- 
#### Solution

In [24]:
celsius_temps = [0, 10, 20, 25, 30, 40, 100]

# 1. Create a NumPy array
celsius_array = np.array(celsius_temps)

# 2. Perform the vectorized calculation
fahrenheit_array = celsius_array * 1.8 + 32

# 3. Print the results
print("Celsius Temps:", celsius_array)
print("Fahrenheit Temps:", fahrenheit_array)

Celsius Temps: [  0  10  20  25  30  40 100]
Fahrenheit Temps: [ 32.  50.  68.  77.  86. 104. 212.]


### What's Next?

Now that we can create and perform math on arrays, how do we select specific elements or sections of them?

Next time, we'll dive into the most powerful features of NumPy: **Indexing and Slicing**, followed by **Aggregations** (like `.sum()`, `.mean()`, `.max()`).

In [ ]:
#universal Function 



In [25]:
arr1 = np.arange(10)
print('Array:\n',arr1)

Array:
 [0 1 2 3 4 5 6 7 8 9]


In [26]:
#square root 
np.sqrt(arr1)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [55]:
#exponential
np.exp(arr1)


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [27]:
x = np.random.randn(10)
y = np.random.randn(10)
print(x)
print(y)

[ 0.05343427 -0.90542521  0.58215507 -0.65621037  0.55966996  2.08523519
 -1.25793725 -0.50394285  1.06626401  2.33057911]
[-0.25205684  0.97118465 -1.1663988  -0.72485401  1.66618399  0.0869037
 -1.20020122 -0.42761699 -0.39181809  1.86043555]


In [28]:
np.minimum(x,y)


array([-0.25205684, -0.90542521, -1.1663988 , -0.72485401,  0.55966996,
        0.0869037 , -1.25793725, -0.50394285, -0.39181809,  1.86043555])

In [58]:
np.maximum(x,y)

array([ 0.80496847,  1.69552248,  0.84777003,  1.02634484,  0.78774606,
       -0.34130529,  0.58376608,  0.87969838,  0.45115962,  0.34384619])

In [59]:
np.min(x)

np.float64(-1.6213924154405295)

In [60]:
np.max(x)

np.float64(0.9410850455496027)

In [61]:
np.sum(x)

np.float64(-2.765827939085579)

In [63]:
z =x*y     #salary with bonus
z

array([-0.06726802,  1.59563085, -0.54512434, -1.66410773, -1.33374892,
        0.52690289, -0.22956072, -0.88380492, -0.41886583, -0.58420622])

In [64]:
np.mean(x)

np.float64(-0.2765827939085579)

In [ ]:
# Array manipulation 


In [29]:
arr = np.array([[3,1,5,3,5],[3,2,5,4,6]])
arr

array([[3, 1, 5, 3, 5],
       [3, 2, 5, 4, 6]])

In [30]:
arr_copy = (arr)
arr_copy

array([[3, 1, 5, 3, 5],
       [3, 2, 5, 4, 6]])

In [67]:
arr_copy.shape

(2, 5)

In [68]:
arr.size

10

In [31]:
arr_copy.sort()

In [32]:
arr_copy

array([[1, 3, 3, 5, 5],
       [2, 3, 4, 5, 6]])

In [33]:
arr_c = np.copy(arr)

In [34]:
arr_c.sort(axis=0)
arr_c

array([[1, 3, 3, 5, 5],
       [2, 3, 4, 5, 6]])

In [35]:
arr.reshape(10,1)

array([[1],
       [3],
       [3],
       [5],
       [5],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [36]:
arr.reshape(5,2)

array([[1, 3],
       [3, 5],
       [5, 2],
       [3, 4],
       [5, 6]])

In [37]:
arr.T

array([[1, 2],
       [3, 3],
       [3, 4],
       [5, 5],
       [5, 6]])

In [38]:
#flattend array # jati dimension ma vaye ni one-D ma lanxa 

arr.ravel()

array([1, 3, 3, 5, 5, 2, 3, 4, 5, 6])

In [ ]:
# solving system of linear equation 
# 2x + 3y - z = 5
# x + 3y - z = 4
# 3x - y + 2z = 7

In [39]:
import numpy as np 
from numpy.linalg import solve, inv, det


In [40]:
A = np.array([[2,3,-1],[1,3,-1],[3,-1,2]])
b = np.array([5,4,7])
A

array([[ 2,  3, -1],
       [ 1,  3, -1],
       [ 3, -1,  2]])

In [41]:
b.shape

(3,)

In [42]:
x, y, z = solve(A,b)

In [99]:
x

np.float64(1.0000000000000002)

In [100]:
y

np.float64(1.9999999999999996)

In [101]:
z

np.float64(2.9999999999999996)

In [102]:
det(A)

np.float64(5.000000000000001)

In [103]:
inv(A)

array([[ 1. , -1. ,  0. ],
       [-1. ,  1.4,  0.2],
       [-2. ,  2.2,  0.6]])

In [104]:
np.round(y)

np.float64(2.0)

In [105]:
np.ceil(x)

np.float64(2.0)

In [106]:
np.floor(x)

np.float64(1.0)

In [107]:
np.abs(-5)

np.int64(5)

In [43]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr1 = np.append(arr, 10) # add garda 1-D mai aauxa 
arr1

array([ 1,  2,  3,  4,  5,  6, 10])

In [45]:
arr2 = np.insert(arr1, 2, 11)
arr2

array([ 1,  2, 11,  3,  4,  5,  6, 10])

In [46]:
arr2 =arr2.reshape(2,4)
arr2

array([[ 1,  2, 11,  3],
       [ 4,  5,  6, 10]])

In [47]:
arr2.size

8

In [48]:
a1 = np.resize(arr2,(2,3))
a1

array([[ 1,  2, 11],
       [ 3,  4,  5]])

In [52]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[11,12,13],[14,15,16]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]


In [70]:
arr2.resize((2,4))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [50]:
a1 = np.resize(arr2,(2,5))
a1

array([[ 1,  2, 11,  3,  4],
       [ 5,  6, 10,  1,  2]])

In [56]:
final= np.concatenate((arr1,arr2), axis=0)
final

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [55]:
np.concatenate((arr1,arr2), axis=1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [62]:
np.split(final,2)   #change upto 1-4

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]])]

In [64]:
np.split(final, 3, axis= 1)

[array([[ 1],
        [ 4],
        [11],
        [14]]),
 array([[ 2],
        [ 5],
        [12],
        [15]]),
 array([[ 3],
        [ 6],
        [13],
        [16]])]

In [65]:
#axis-1
np.hsplit(final,3)
#h= horizontal


[array([[ 1],
        [ 4],
        [11],
        [14]]),
 array([[ 2],
        [ 5],
        [12],
        [15]]),
 array([[ 3],
        [ 6],
        [13],
        [16]])]

In [66]:
#axis = 0
np.vsplit(final,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]])]

In [67]:
#statistical 
final

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [69]:
print(np.mean(final))
print(np.mean(final,axis=0))
print(np.mean(final, axis=1))


8.5
[7.5 8.5 9.5]
[ 2.  5. 12. 15.]


np.var(final)
