# Numpy : Day-3


## Part 4: The Magic - Basic Math and Vectorization 

### The Core Concept: Vectorization

This is the payoff! Let's revisit our initial problem of adding 5 to one million numbers, but this time, we'll use NumPy.

In [10]:
# The "fast" way with NumPy
numpy_array = np.arange(1_000_000)

# Start the timer
start_time = time.time()

# This is vectorization! The operation is applied to every element.
result_array = numpy_array + 5 

end_time = time.time()
print(f"NumPy array took: {end_time - start_time:.4f} seconds") 
print(f"First 10 elements of the result array: {result_array[:10]}")

NumPy array took: 0.0047 seconds
First 10 elements of the result array: [ 5  6  7  8  9 10 11 12 13 14]


**Vectorization** is the process of performing an operation on the entire array at once, without needing an explicit Python `for` loop. This is the heart of NumPy's power and convenience.

### Element-wise Operations

All standard mathematical operations work in a vectorized, element-wise fashion.

#### Array-Scalar Operations

In [11]:
arr = np.array([10, 20, 30, 40])

print("Original:", arr)
print("Addition:", arr + 5)      
print("Subtraction:", arr - 10)
print("Multiplication:", arr * 2) 
print("Division:", arr / 10)
print("Power:", arr ** 2)

Original: [10 20 30 40]
Addition: [15 25 35 45]
Subtraction: [ 0 10 20 30]
Multiplication: [20 40 60 80]
Division: [1. 2. 3. 4.]
Power: [ 100  400  900 1600]


#### Array-Array Operations
To perform an operation between two arrays, they must have the same shape.

In [12]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("a:", a)
print("b:", b)
print("a + b:", a + b)
print("a * b:", a * b)

a: [1 2 3]
b: [10 20 30]
a + b: [11 22 33]
a * b: [10 40 90]


In [13]:
# This also works for 2D arrays!
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.ones((2, 2))

print("Matrix A:\n", matrix_a)
print("\nMatrix B:\n", matrix_b)
print("\nMatrix A + Matrix B:\n", matrix_a + matrix_b)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[1. 1.]
 [1. 1.]]

Matrix A + Matrix B:
 [[2. 3.]
 [4. 5.]]


## Part 5: Wrap-up & Mini-Challenge 

### Recap of Key Concepts

*   NumPy is for **numerical** data and is **fast**, **memory-efficient**, and **convenient**.
*   The core object is the `ndarray`, which holds a grid of **same-typed** data.
*   We create arrays with `np.array()`, `np.arange()`, `np.zeros()`, `np.linspace()`.
*   We inspect them with the attributes `.shape`, `.ndim`, `.size`, `.dtype`.
*   **Vectorization** is the magic that lets us perform math on entire arrays without loops, and it's the key to writing clean and fast NumPy code.

### Mini-Challenge: Celsius to Fahrenheit

You have a list of temperatures in Celsius. Your task is to convert them to Fahrenheit.

**Formula:** `F = C * 1.8 + 32`

In [14]:
celsius_temps = [0, 10, 20, 25, 30, 40, 100]

# Your task:
# 1. Create a NumPy array from the celsius_temps list.


# 2. Perform the vectorized calculation to convert them to Fahrenheit.


# 3. Print the resulting Fahrenheit temperatures.



--- 
#### Solution

In [15]:
celsius_temps = [0, 10, 20, 25, 30, 40, 100]

# 1. Create a NumPy array
celsius_array = np.array(celsius_temps)

# 2. Perform the vectorized calculation
fahrenheit_array = celsius_array * 1.8 + 32

# 3. Print the results
print("Celsius Temps:", celsius_array)
print("Fahrenheit Temps:", fahrenheit_array)

Celsius Temps: [  0  10  20  25  30  40 100]
Fahrenheit Temps: [ 32.  50.  68.  77.  86. 104. 212.]


### What's Next?

Now that we can create and perform math on arrays, how do we select specific elements or sections of them?

Next time, we'll dive into the most powerful features of NumPy: **Indexing and Slicing**, followed by **Aggregations** (like `.sum()`, `.mean()`, `.max()`).